### ISSUE TITLE
Prototipo

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/diseno-de-prototipo-en-adobe-xd-o-figma-pc-box#2]
[MOCK UP.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-prototipo-en-adobe-xd-o-figma-pc-box/files/6361813/MOCK.UP.pdf)

**Comment by 10154** [comment]
El trabajo esta muy bien estructurado por lo que obtuvo 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
